configMapGenerator:
  - behavior: merge
    files:
      - values.yaml=configmap.yaml
    name: common
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://repo1.dso.mil/platform-one/big-bang/bigbang.git/base?ref=3.21.0
  - flux-components.yaml
patches:
  - path: common-bb-secret.enc.yaml
